Traceback (most recent call last):
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/raminasser/anaconda3/envs/software_project/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rand(d0,d1,...,dn) #Random values in a given shape
randn(d0, d1, ...,dn) #Random standard normal
randint(lo, hi, size) #Random integers [lo, hi)
choice(a, size, repl, p) #Sample from a
shuffle(a) #Permutation (in-place)
permutation(a) #Permutation (new array)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[61], line 1[0m
[0;32m----> 1[0m [43mrand[49m(d0,d1,[38;5;241m.[39m[38;5;241m.[39m[38;5;241m.[39m,dn) [38;5;66;03m#Random values in a given shape[39;00m
[1;32m      2[0m randn(d0, d1, [38;5;241m.[39m[38;5;241m.[39m[38;5;241m.[39m,dn) [38;5;66;03m#Random standard normal[39;00m
[1;32m      3[0m randint(lo, hi, size) [38;5;66;03m#Random integers [lo, hi)[39;00m

[0;31mNameError[0m: name 'rand' is not defined

